const urls = {
  userLoginUrl: 'login',
  userSignup: 'signup',
  getStores: 'getStores',
  getMenusByHotelId: 'getMenus',
  getUserDetails: 'getUserDetails',
  updateUser: 'updateUser',
  updatePassword: 'changePassword',
  submitOrder: 'submitOrder',
  inviteForEvent: 'inviteForEvent',
  addCard: 'addCard',
  getCards: 'getCards',
  getCardDetail: 'getCardDetail',
  getOrders: 'getOrders',
  deleteCard: 'deleteCard',
  findUpcomingEvents: 'findUpcomingEvents',
  getEventDetails: 'getEventDetails',
  getNotifications: 'getNotifications',
  forgotPassword: 'forgotPassword',
  acceptOrRejectInvitation: 'acceptOrRejectInvitation',
  getOrderDetails: 'getOrderDetails',
  getUpcomingGifts: 'getUpcomingGifts',
  getPastGifts: 'getPastGifts',
  getOrderInfo: 'getOrderInfo',
  redeemItem: 'redeemItem',
  getOrderSecretInfo: 'getOrderSecretInfo',
  getCities: 'getCities',
  addMobileDeviceData: 'addMobileDeviceData',
};

export default urls;
